#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require npx parallel sql-formatter
if [[ -z "$*" ]]; then
  echo "Usage: "
  echo "$0 <list of files>"
  exit 1
fi
RED='\033[0;31m'
NC='\033[0m' # No Color
declare -i exitcode=0
declare -a files=("$@")
echo -e "${RED}Formatting with sql-formatter${NC}"
parallel ./formatfile ::: "${files[@]}"
exitcode=$?
if [[ "$exitcode" -eq 0 ]]; then
  echo -e "${RED}Formatting with prettier${NC}"
  parallel npx prettier --write ::: "${files[@]}"
  exitcode=$?
fi
exit "$exitcode"
