#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require npx parallel
if [[ -z "$*" ]]; then
  echo "Usage: "
  echo "$0 <list of files>"
  exit 1
fi
declare -i exitcode=0
declare -a files=("$@")
parallel npx prettier --write ::: "${files[@]}"
exit $(("$exitcode" + $?))
