#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require sqlfluff
rm -f lint.out
sqlfluff fix --dialect sqlite -- *.sql
declare -i exitcode=$?
if [[ $exitcode != 0 ]]; then
  sqlfluff lint --dialect sqlite -- *.sql &> lint.out
  exitcode=$?
  if [[ $exitcode != 0 ]]; then
    echo "Errors found. Check lint.out"
  fi
fi
exit "$exitcode"
